name: levy_shared_entities
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  levy_core:
    path: ../levy_core

  levy_dependencies:
    path: ../levy_dependencies
  #    git:
  #      url: https://github.com/andreleitejr/levy_dependencies.git

  json_annotation:
  google_maps_flutter:
  riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4